# Generated by Django 5.2.10 on 2026-02-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='driver_rejection_count',
            new_name='driver_rejections_count',
        ),
    ]
