# Generated by Django 5.2.10 on 2026-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_driverprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
