# Generated by Django 5.2.10 on 2026-02-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customerprofile_customer_id_driverprofile_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='driver_id',
        ),
    ]
