# Generated by Django 5.2.10 on 2026-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_driverprofile_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
