# Generated by Django 5.2.10 on 2026-03-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
